"""
visualizer/report_generator.py
================================
Generate a clean multi-page PDF report summarising an OT-2 protocol run (Christian Chung).
"""

import math
import os

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import matplotlib.patches as mpatches
from matplotlib.backends.backend_pdf import PdfPages
from matplotlib.figure import Figure

from .log_parser import ParsedProtocol
from .state_tracker import DeckSnapshot, is_tracked_plate
from .deck_visualizer import render_deck_snapshot
from .plate_visualizer import CMAP_VOLUME

_BG     = "#FFFFFF"
_TEXT   = "#1E2130"
_DIM    = "#6B7280"
_ACCENT = "#2563EB"
_PANEL  = "#F0F2F7"
_BORDER = "#C4C9D8"

_ROWS = list("ABCDEFGH")
_COLS = list(range(1, 13))
_ROWS_PER_LOG_PAGE = 35


def generate_report(protocol: ParsedProtocol, snapshots: list, output_path: str) -> None:
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)

    with PdfPages(output_path) as pdf:
        _page_cover(pdf, protocol, snapshots)

        fig = render_deck_snapshot(snapshots[0], protocol)
        pdf.savefig(fig, bbox_inches="tight")
        plt.close(fig)

        fig = render_deck_snapshot(snapshots[-1], protocol)
        pdf.savefig(fig, bbox_inches="tight")
        plt.close(fig)

        tracked = sorted(
            (s for s, lw in protocol.slot_labware.items() if is_tracked_plate(lw)),
            key=lambda s: (0, int(s)) if s.isdigit() else (1, s),
        )
        for slot in tracked:
            _page_plate_compare(pdf, slot, snapshots[0], snapshots[-1], protocol)

        _pages_step_log(pdf, protocol)


def _page_cover(pdf, protocol, snapshots):
    fig, ax = plt.subplots(figsize=(11, 8.5), facecolor=_BG)
    ax.set_axis_off()

    ax.add_patch(mpatches.FancyBboxPatch((0, 0.83), 1.0, 0.17, boxstyle="square,pad=0",
                                          transform=ax.transAxes, facecolor=_ACCENT,
                                          edgecolor="none", clip_on=False))
    ax.text(0.5, 0.915, protocol.protocol_name, transform=ax.transAxes,
            ha="center", va="center", fontsize=18, fontweight="bold", color="white",
            fontfamily="monospace")
    ax.text(0.5, 0.855, "OT-2 Simulation Protocol Report", transform=ax.transAxes,
            ha="center", va="center", fontsize=11, color="white", alpha=0.85)

    n_steps   = len(protocol.steps)
    n_labware = len(protocol.slot_labware)
    n_tracked = sum(1 for lw in protocol.slot_labware.values() if is_tracked_plate(lw))

    _draw_box(ax, 0.03, 0.46, 0.40, 0.32)
    ax.text(0.06, 0.758, "Summary", transform=ax.transAxes, fontsize=11, fontweight="bold", color=_TEXT)
    for i, (label, val) in enumerate([("Pipetting steps", str(n_steps)),
                                       ("Labware items", str(n_labware)),
                                       ("Tracked plates", str(n_tracked)),
                                       ("Deck snapshots", str(len(snapshots)))]):
        y = 0.715 - i * 0.062
        ax.text(0.065, y, label + ":", transform=ax.transAxes, fontsize=9, color=_DIM)
        ax.text(0.40, y, val, transform=ax.transAxes, fontsize=9, color=_ACCENT, fontweight="bold", ha="right")

    _draw_box(ax, 0.52, 0.46, 0.45, 0.32)
    ax.text(0.555, 0.758, "Labware Layout", transform=ax.transAxes, fontsize=11, fontweight="bold", color=_TEXT)
    for i, slot in enumerate(sorted(protocol.slot_labware, key=lambda s: (0, int(s)) if s.isdigit() else (1, s))[:8]):
        lw    = protocol.slot_labware[slot]
        short = lw if len(lw) <= 30 else lw[:29] + "…"
        y     = 0.715 - i * 0.052
        ax.text(0.555, y, f"Slot {slot:>2}:", transform=ax.transAxes, fontsize=8.5, color=_DIM, fontfamily="monospace")
        ax.text(0.638, y, short, transform=ax.transAxes, fontsize=8.5, color=_TEXT, fontfamily="monospace")

    ax.text(0.5, 0.425, "Deck Layout", transform=ax.transAxes, ha="center", fontsize=10, fontweight="bold", color=_TEXT)
    _draw_deck_grid(ax, protocol)

    ax.text(0.5, 0.015, "Generated by OT-2 Simulation Log Visualizer  •  BIOE234 Final Project",
            transform=ax.transAxes, ha="center", fontsize=8, color=_DIM)

    pdf.savefig(fig, bbox_inches="tight")
    plt.close(fig)


def _draw_box(ax, x, y, w, h):
    ax.add_patch(mpatches.FancyBboxPatch((x, y), w, h, boxstyle="round,pad=0.01",
                                          transform=ax.transAxes, facecolor=_PANEL,
                                          edgecolor=_BORDER, linewidth=1.0, clip_on=False))


def _draw_deck_grid(ax, protocol):
    GRID_POS = {
        "1":  (0, 0), "2":  (0, 1), "3":  (0, 2),
        "4":  (1, 0), "5":  (1, 1), "6":  (1, 2),
        "7":  (2, 0), "8":  (2, 1), "9":  (2, 2),
        "10": (3, 0), "11": (3, 1), "12": (3, 2),
    }
    x0, x1, y0, y1 = 0.04, 0.96, 0.06, 0.40
    col_w = (x1 - x0) / 3
    row_h = (y1 - y0) / 4

    for slot, (deck_row, col) in GRID_POS.items():
        gx = x0 + col * col_w
        gy = y0 + deck_row * row_h
        lw = protocol.slot_labware.get(slot, "")
        is_trash = slot == "12"
        face = "#FEE2E2" if is_trash else ("#DBEAFE" if lw else _PANEL)

        ax.add_patch(mpatches.FancyBboxPatch((gx + 0.004, gy + 0.003), col_w - 0.008, row_h - 0.006,
                                              boxstyle="round,pad=0.003", transform=ax.transAxes,
                                              facecolor=face, edgecolor=_BORDER, linewidth=0.7, clip_on=False))
        ax.text(gx + 0.013, gy + row_h - 0.012, "Trash" if is_trash else f"Slot {slot}",
                transform=ax.transAxes, va="top", fontsize=5.5, color=_DIM, fontfamily="monospace")
        body = ("Fixed Trash" if is_trash else lw) if lw else "—"
        if len(body) > 24:
            body = body[:23] + "…"
        ax.text(gx + col_w / 2, gy + row_h / 2, body, transform=ax.transAxes,
                ha="center", va="center", fontsize=5.5, color=_TEXT, fontfamily="monospace")


def _page_plate_compare(pdf, slot, snap_init, snap_final, protocol):
    lw_name = protocol.slot_labware.get(slot, f"Slot {slot}")
    max_vol = max(snap_init.slot_max_volumes.get(slot, 200.0),
                  snap_final.slot_max_volumes.get(slot, 200.0)) or 1.0

    fig, axes = plt.subplots(1, 2, figsize=(13, 5), facecolor=_BG, gridspec_kw={"wspace": 0.08})
    fig.suptitle(f"Plate Comparison  —  Slot {slot}: {lw_name}",
                 color=_TEXT, fontsize=11, fontweight="bold", fontfamily="monospace")

    for ax, snap, subtitle in zip(axes, [snap_init, snap_final], ["Initial State", "Final State"]):
        _draw_heatmap_ax(ax, slot, snap, max_vol, subtitle)

    sm = plt.cm.ScalarMappable(cmap=CMAP_VOLUME, norm=mcolors.Normalize(vmin=0, vmax=1))
    sm.set_array([])
    cbar = fig.colorbar(sm, ax=axes, fraction=0.025, pad=0.02)
    cbar.set_label(f"Volume (µL)  /  max = {max_vol:.0f} µL", color=_TEXT, fontsize=8)
    tick_fracs = [0, 0.25, 0.5, 0.75, 1.0]
    cbar.set_ticks(tick_fracs)
    cbar.set_ticklabels([f"{int(f * max_vol)}" for f in tick_fracs], color=_TEXT, fontsize=7.5)
    cbar.ax.yaxis.set_tick_params(color=_TEXT)

    fig.subplots_adjust(top=0.91, bottom=0.06, left=0.06, right=0.88, wspace=0.08)
    pdf.savefig(fig, bbox_inches="tight")
    plt.close(fig)


def _draw_heatmap_ax(ax, slot, snapshot, max_vol, subtitle):
    vol_grid = np.zeros((8, 12))
    for r, row in enumerate(_ROWS):
        for c, col in enumerate(_COLS):
            vol_grid[r, c] = snapshot.well_volumes.get((slot, f"{row}{col}"), 0.0)
    fill_grid = np.clip(vol_grid / max_vol, 0.0, 1.0)

    ax.imshow(fill_grid, cmap=CMAP_VOLUME, vmin=0, vmax=1, aspect="auto", interpolation="nearest")
    ax.set_facecolor(_BG)

    for r in range(8):
        for c in range(12):
            vol = vol_grid[r, c]
            fill = fill_grid[r, c]
            if vol > 0.5:
                txt_col = "white" if fill > 0.5 else _TEXT
                label = f"{vol:.0f}" if vol < 1000 else f"{vol/1000:.1f}k"
                ax.text(c, r, label, ha="center", va="center",
                        fontsize=6, color=txt_col, fontweight="bold", fontfamily="monospace")

    ax.set_yticks(range(8))
    ax.set_yticklabels(_ROWS, color=_TEXT, fontsize=8, fontfamily="monospace")
    ax.yaxis.set_tick_params(length=0)
    ax.set_xticks(range(12))
    ax.set_xticklabels([str(c) for c in _COLS], color=_TEXT, fontsize=8, fontfamily="monospace")
    ax.xaxis.set_tick_params(length=0)
    ax.xaxis.set_ticks_position("top")
    ax.xaxis.set_label_position("top")
    for spine in ax.spines.values():
        spine.set_edgecolor(_BORDER)
        spine.set_linewidth(0.8)
    ax.set_title(subtitle, color=_TEXT, fontsize=9, fontfamily="monospace", pad=4)


def _pages_step_log(pdf, protocol):
    headers    = ["Step", "Action", "Vol (µL)", "Slot", "Well", "Labware"]
    col_widths = [0.06, 0.14, 0.10, 0.06, 0.07, 0.57]

    rows = []
    for step in protocol.steps:
        rows.append([
            str(step.step_index),
            step.action.replace("_", " ").title(),
            f"{step.volume_ul:.1f}" if step.volume_ul is not None else "—",
            step.slot or "—",
            step.well or "—",
            step.labware or "—",
        ])

    n_pages = max(1, math.ceil(len(rows) / _ROWS_PER_LOG_PAGE))
    for page in range(n_pages):
        chunk = rows[page * _ROWS_PER_LOG_PAGE: (page + 1) * _ROWS_PER_LOG_PAGE]
        fig = _render_log_table(headers, chunk, col_widths,
                                title=f"Step Log  (page {page + 1} of {n_pages})",
                                subtitle=protocol.protocol_name)
        pdf.savefig(fig, bbox_inches="tight")
        plt.close(fig)


def _render_log_table(headers, rows, col_widths, title, subtitle):
    n_data = len(rows)
    fig_h  = max(4.5, 1.5 + n_data * 0.22 + 0.5)
    fig, ax = plt.subplots(figsize=(11, fig_h), facecolor=_BG)
    ax.set_axis_off()

    ax.text(0.5, 0.985, title, transform=ax.transAxes, ha="center", va="top",
            fontsize=11, fontweight="bold", color=_TEXT)
    ax.text(0.5, 0.955, subtitle, transform=ax.transAxes, ha="center", va="top",
            fontsize=8.5, color=_DIM, fontfamily="monospace")

    table_top  = 0.91
    total_rows = n_data + 1
    row_h = (table_top - 0.06) / total_rows

    _draw_row(ax, 0.01, table_top - row_h, row_h, col_widths, headers,
              bg=_ACCENT, fg="white", fs=8.5, bold=True)
    for i, row in enumerate(rows):
        y  = table_top - (i + 2) * row_h
        bg = _PANEL if i % 2 == 0 else _BG
        _draw_row(ax, 0.01, y, row_h, col_widths, row, bg=bg, fg=_TEXT, fs=7.5, bold=False)

    ax.text(0.5, 0.015, "OT-2 Simulation Log Visualizer  •  BIOE234 Final Project",
            transform=ax.transAxes, ha="center", fontsize=7.5, color=_DIM)
    return fig


def _draw_row(ax, x0, y0, row_h, col_widths, values, bg, fg, fs, bold):
    total_w = 1.0 - 2 * x0
    x = x0
    for frac, val in zip(col_widths, values):
        w = frac * total_w
        ax.add_patch(mpatches.FancyBboxPatch((x, y0), w, row_h, boxstyle="square,pad=0",
                                              transform=ax.transAxes, facecolor=bg,
                                              edgecolor=_BORDER, linewidth=0.3, clip_on=False))
        ax.text(x + 0.005 * total_w, y0 + row_h * 0.5, str(val), transform=ax.transAxes,
                va="center", ha="left", fontsize=fs, color=fg,
                fontweight="bold" if bold else "normal", fontfamily="monospace")
        x += w
